/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AllRecipesImport } from './routes/AllRecipes'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AllRecipesRoute = AllRecipesImport.update({
  path: '/AllRecipes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/AllRecipes': {
      id: '/AllRecipes'
      path: '/AllRecipes'
      fullPath: '/AllRecipes'
      preLoaderRoute: typeof AllRecipesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, AllRecipesRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/AllRecipes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/AllRecipes": {
      "filePath": "AllRecipes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
